import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {buildPreviewModel} from '../lib/box-model';
const NAMES:Record<string,string>={tianlide:'Lift-off lid box',drawer:'Drawer box',flip:'Hinged lid box',book:'Book-style box',foldable_flip:'Fold-flat hinged box',window_flip:'Window hinged box',double_door:'Double-door box',shoulder:'Shoulder box',airplane:'Mailer box',rsc:'Shipping carton',tuck:'Tuck-end carton',paperbag:'Paper shopping bag'};
const cache=new Map<string,string>();
export default function BoxThumbnail({type,decorative=false,dimensions,options}:{type:string;decorative?:boolean;dimensions?:{length:number;width:number;height:number};options?:{paperColor:string;surface:string;opening:number}}){
 const cacheKey=JSON.stringify([type,dimensions,options]);
 const [visible,setVisible]=useState(false);
 const [src,setSrc]=useState(cache.get(cacheKey)||''),[failed,setFailed]=useState(false);const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!host.current)return;if(!('IntersectionObserver' in window)){setVisible(true);return}const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setVisible(true);observer.disconnect()}},{rootMargin:'120px'});observer.observe(host.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!visible)return;setSrc(cache.get(cacheKey)||'');setFailed(false);if(cache.has(cacheKey))return;let cancelled=false;const timer=setTimeout(()=>{let renderer:THREE.WebGLRenderer|undefined;const scene=new THREE.Scene();try{
 renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(720,500);renderer.setPixelRatio(1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
 scene.background=new THREE.Color('#f4f1ea');scene.add(new THREE.HemisphereLight('#ffffff','#b3aa98',2));const light=new THREE.DirectionalLight('#fff3df',3);light.position.set(-170,380,260);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-350,right:350,top:350,bottom:-350,near:1,far:1000});light.shadow.bias=-.001;scene.add(light);
 const tall=['tuck','paperbag'].includes(type),l=dimensions?.length||(tall?110:220),w=dimensions?.width||(tall?65:150),h=dimensions?.height||(tall?180:75);const paper=new THREE.MeshStandardMaterial({color:options?.paperColor||(['airplane','rsc','paperbag'].includes(type)?'#b99a70':'#315e50'),roughness:options?.surface==='gloss'?.22:.78});const {root}=buildPreviewModel(type,l,w,h,['airplane','rsc'].includes(type)?2:1.8,1,options?.opening??55,paper);scene.add(root);
 const bounds=new THREE.Box3().setFromObject(root),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const span=Math.max(size.x,size.y,size.z)*1.3;const camera=new THREE.PerspectiveCamera(35,720/500,1,3000);camera.position.copy(center).add(new THREE.Vector3(span*1.25,span*.9,span*1.65));camera.lookAt(center);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(2500,2500),new THREE.ShadowMaterial({opacity:.14}));floor.rotation.x=-Math.PI/2;floor.position.y=bounds.min.y-.3;floor.receiveShadow=true;scene.add(floor);renderer.render(scene,camera);const url=renderer.domElement.toDataURL('image/webp',.88);cache.set(cacheKey,url);if(!cancelled)setSrc(url);
 }catch{if(!cancelled)setFailed(true)}finally{scene.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>x.dispose())});renderer?.dispose();renderer?.forceContextLoss()}},0);return()=>{cancelled=true;clearTimeout(timer)}},[cacheKey,visible]);
 return <div ref={host} className={`box-thumb box-illustration box-thumb-${type}`} style={{aspectRatio:'36 / 25',overflow:'hidden',background:'#f4f1ea',borderRadius:12}}>{src?<img src={src} alt={decorative?'':`${NAMES[type]} — illustrative assembled structure`} style={{width:'100%',height:'100%',objectFit:'contain'}}/>:<p>{failed?'Preview unavailable — ': 'Loading preview — '}{NAMES[type]}</p>}</div>
}
