import {tr} from '../lib/tool-language.mjs';
"use client";
/* eslint-disable @next/next/no-img-element -- local customer artwork */
import {useState} from 'react';
import {type GiftOptions} from './GiftBoxPreview';
import {FACES,imageArtwork,normalizeArtwork,textArtwork} from '../lib/artwork.mjs';
import {availableFaces,clearWhiteBackground} from '../lib/image-placement.mjs';
import {layoutOptions,layoutTransform,suggestedUsage} from '../lib/auto-layout.mjs';
import StructurePreview from './StructurePreview';
export type Artwork={id:string;kind:string;face:string;text?:string;src?:string;name?:string;x:number;y:number;size:number;color:string;finish?:string;fit?:string;usage?:string;hidden?:boolean;locked?:boolean;pixelWidth?:number;pixelHeight?:number;whiteBackground?:boolean;hasTransparency?:boolean;maskConfirmed?:boolean};
export default function DesignStudio({box,artworks,onChange,visualOptions,onVisualChange,defaultFinish="print",onUploadIssue,settingsPanel}:{settingsPanel?:import('react').ReactNode;onUploadIssue?:(name:string)=>void;defaultFinish?:string;visualOptions?:GiftOptions;onVisualChange?:(value:GiftOptions)=>void;box:ReturnType<typeof import('../lib/packaging.mjs').buildBox>;artworks:Artwork[];onChange:(items:Artwork[])=>void}){
 const [originals,setOriginals]=useState<Record<string,Artwork>>({});
 const [selectedId,setSelectedId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState<{x:number;y:number}|null>(null);
 const selected=artworks.find(a=>a.id===selectedId)||artworks[artworks.length-1],faces=availableFaces(box.id);
 function add(item:Artwork){if(artworks.length>=20){setError('Maximum 20 layers. Remove an unused layer before adding more.');return}item={...item,finish:item.finish||(item.kind==='image'?'print':defaultFinish)};onChange([...artworks,item]);setSelectedId(item.id)}
 function patch(value:Partial<Artwork>,force=false){if(selected&&(!selected.locked||force))onChange(artworks.map(item=>item.id===selected.id?normalizeArtwork({...item,...value}):item))}
 async function upload(file?:File,replace=false){if(!file||replace&&selected?.locked)return;setError('');if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>20*1024*1024){onUploadIssue?.(file.name);setError('Choose a PNG, JPG or WebP image under 20 MB.');return}setBusy(true);const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const ratio=Math.min(1,1600/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*ratio));canvas.height=Math.max(1,Math.round(img.height*ratio));canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);let src=canvas.toDataURL('image/webp',.9);if(src.length>2000000)src=canvas.toDataURL('image/webp',.65);const data=canvas.getContext('2d')!.getImageData(0,0,canvas.width,canvas.height).data;let white=false,alpha=false;for(let i=0;i<data.length;i+=4){if(data[i+3]<250)alpha=true;if(data[i]>240&&data[i+1]>240&&data[i+2]>240&&data[i+3]>250&&(i<canvas.width*4||i>=data.length-canvas.width*4||i%(canvas.width*4)===0||(i+4)%(canvas.width*4)===0))white=true;}onUploadIssue?.('');const item={pixelWidth:canvas.width,pixelHeight:canvas.height,whiteBackground:white,hasTransparency:alpha,...imageArtwork(src,file.name),face:faces.includes('top')?'top':'front',fit:'contain',size:70};const usage=suggestedUsage(item);if(replace&&selected){patch({...item,id:selected.id,face:selected.face,x:selected.x,y:selected.y,size:selected.size,fit:selected.fit||'contain',finish:'print',maskConfirmed:false,usage});setOriginals(old=>{const next={...old};delete next[selected.id];return next})}else{add({...item,usage,...layoutTransform(layoutOptions(usage)[0])})}}catch{onUploadIssue?.(file.name);setError('Cannot read this image. Try another PNG or JPG.')}finally{URL.revokeObjectURL(url);setBusy(false)}}
 async function removeWhite(){if(!selected?.src||selected.locked)return;setBusy(true);setError('');try{const img=new Image();img.src=selected.src;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(img,0,0);const pixels=ctx.getImageData(0,0,img.width,img.height);pixels.data.set(clearWhiteBackground(pixels.data,img.width,img.height));ctx.putImageData(pixels,0,0);let minX=img.width,minY=img.height,maxX=-1,maxY=-1;for(let y=0;y<img.height;y++)for(let x=0;x<img.width;x++)if(pixels.data[(y*img.width+x)*4+3]>0){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}if(maxX<0){setError('No visible artwork remains. The original image has been kept.');return}const crop=document.createElement('canvas');crop.width=maxX-minX+1;crop.height=maxY-minY+1;crop.getContext('2d')!.drawImage(canvas,minX,minY,crop.width,crop.height,0,0,crop.width,crop.height);setOriginals(old=>({...old,[selected.id]:old[selected.id]||selected}));patch({pixelWidth:crop.width,pixelHeight:crop.height,whiteBackground:false,hasTransparency:crop.getContext('2d')!.getImageData(0,0,crop.width,crop.height).data.some((v,i)=>i%4===3&&v<250),src:crop.toDataURL('image/webp',.92),fit:'contain',x:50,y:50});}catch{setError('Cannot process this image. The original has been kept.')}finally{setBusy(false)}}
 const face=selected?.face||'front',d=box.dimensions,fw=['left','right'].includes(face)?d.width:d.length,fh=['top','bottom'].includes(face)?d.width:d.height;
 return <div className="design-layout"><section className="design-controls"><h2>{tr("Place your design on the box")}</h2><p>{tr("Upload an image, choose its purpose, then select a layout. Images stay complete by default. Undo or adjust anytime.")}</p>{settingsPanel}<div className="add-buttons"><button disabled={busy} onClick={()=>add(textArtwork())}>{tr("＋ Add text")}</button><label>{busy?'Preparing image…':'＋ Upload logo / image'}<input disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label></div>{error&&<p role="alert">{error}</p>}
 {artworks.length>0&&<><div className="art-list">{artworks.map(item=>item.kind==='text'&&item.id===selected?.id?<label className="direct-text-edit" key={item.id}>{tr("Text content")}<input aria-label="Text content" disabled={busy||item.locked} maxLength={300} value={item.text||''} placeholder="Enter your brand name or packaging text" onChange={e=>patch({text:e.target.value})}/><small>{item.locked?tr("This layer is locked. Choose Unlock layer below to edit."):tr("Type here to update the preview.")}</small></label>:<button className={item.id===selected?.id?'selected':''} key={item.id} disabled={busy} onClick={()=>setSelectedId(item.id)}>{item.kind==='text'?`Text: ${item.text}`:`Image: ${item.name||'Logo'}`}</button>)}</div>{selected&&<div className="art-fields">
 {selected.kind==='image'&&<section className="smart-layout" aria-label="Layout suggestions"><h3>{tr("Choose a layout")}</h3><p>{tr("Suggestions use image transparency. Confirm the purpose; product recognition and automatic cutout are not included.")}</p><label>{tr("Use this image as")}<select aria-label="Image purpose" disabled={busy||selected.locked} value={selected.usage||suggestedUsage(selected)} onChange={e=>patch({usage:e.target.value})}><option value="logo">{tr("Logo / brand mark")}</option><option value="photo">{tr("Product photo / full image")}</option><option value="background">{tr("Background / pattern")}</option></select></label><div className="smart-layout-options">{layoutOptions(selected.usage||suggestedUsage(selected)).map((option,index)=><button type="button" key={option.id} disabled={busy||selected.locked||selected.hidden} aria-label={`Apply layout: ${option.name}`} aria-pressed={selected.x===option.x&&selected.y===option.y&&selected.size===option.size&&selected.fit===option.fit} onClick={()=>patch(layoutTransform(option))}><span className="smart-layout-thumb" style={{aspectRatio:`${fw}/${fh}`,background:visualOptions?.paperColor||'#244438'}}><img alt="" src={selected.src} style={{left:`${option.x}%`,top:`${option.y}%`,width:`${option.size}%`,height:`${option.size}%`,objectFit:option.fit==='cover'?'cover':'contain'}}/></span><strong>{option.name}{index===0?' · Suggested':''}</strong><small>{option.reason}</small></button>)}</div><p>{tr("Select a layout to update the face and 3D preview. Placement scales with box dimensions. Use Undo to revert.")}</p>{selected.fit==='cover'&&<p role="status">{tr("Fill mode may crop image edges. Use Fit for logos, text or important subjects.")}</p>}{selected.whiteBackground&&!selected.hasTransparency&&<p>{tr("White edges detected. For a logo, try Remove white background and trim. Keep product photos intact unless removal is intended.")}</p>}<label className="smart-replace">{tr("Replace image (keep position)")}<input type="file" disabled={busy||selected.locked} accept="image/png,image/jpeg,image/webp" onChange={e=>{upload(e.target.files?.[0],true);e.target.value=''}}/></label></section>}
 <div className="placement-actions"><button disabled={busy} onClick={()=>patch({locked:!selected.locked},true)}>{selected.locked?tr("Unlock layer"):tr("Lock layer")}</button><button disabled={busy} onClick={()=>patch({hidden:!selected.hidden},true)}>{selected.hidden?tr("Show layer"):tr("Hide layer")}</button>{[-1,1].map(delta=><button key={delta} disabled={selected.locked||artworks.indexOf(selected)+delta<0||artworks.indexOf(selected)+delta>=artworks.length} onClick={()=>{const copy=[...artworks],i=copy.indexOf(selected);[copy[i],copy[i+delta]]=[copy[i+delta],copy[i]];onChange(copy)}}>{delta===1?tr("Move layer up"):tr("Move layer down")}</button>)}</div><fieldset disabled={selected.locked||busy} className="v21-art-fieldset"><label>{tr("Box face")}<select aria-label="Box face" value={selected.face} onChange={e=>patch({face:e.target.value,x:50,y:50})}>{FACES.map(f=><option key={f.id} disabled={!faces.includes(f.id)} value={f.id}>{({front:tr("Front"),back:tr("Back"),left:tr("Left"),right:tr("Right"),top:tr("Top"),bottom:tr("Bottom")} as Record<string,string>)[f.id]}{!faces.includes(f.id)?' (full artwork unavailable)':''}</option>)}</select></label>
 {!faces.includes(selected.face)&&<p className="warning">{tr("Full artwork is not supported on this face. Choose the front or a side.")}</p>}
 <div className="art-placement" role="group" aria-label="Artwork positioning area" style={{aspectRatio:`${fw}/${fh}`,width:`min(100%, ${Math.max(20,Math.round(420*fw/fh))}px)`,background:visualOptions?.paperColor||'#244438'}} onPointerDown={e=>{if(selected.locked||busy||selected.hidden)return;e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();setDrag({x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))})}} onPointerMove={e=>{if(!drag)return;const r=e.currentTarget.getBoundingClientRect();setDrag({x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))})}} onPointerUp={()=>{if(drag)patch(drag);setDrag(null)}} onPointerCancel={()=>setDrag(null)}>
 {artworks.filter(a=>a.face===face&&!a.hidden).map(a=><div key={a.id} className={a.id===selected.id?'placement-art current':'placement-art'} style={{left:`${a.id===selected.id&&drag?drag.x:a.x}%`,top:`${a.id===selected.id&&drag?drag.y:a.y}%`,width:`${a.size}%`,height:a.kind==='image'&&a.fit!=='width'?`${a.size}%`:undefined,color:a.color}}>{a.kind==='image'?<img src={a.src} alt="Artwork placement" draggable={false} style={{height:a.fit!=='width'?'100%':'auto',objectFit:a.fit==='cover'?'cover':'contain'}}/>:<span>{a.text}</span>}</div>)}
 </div><small>{tr("Drag to position, then release to update 3D. The dashed outline marks the selected layer. Position sliders support keyboard adjustment.")}</small>
 <div className="placement-actions"><button onClick={()=>patch({x:50,y:50,fit:'contain',size:70})}>{tr("Fit logo")}</button><button onClick={()=>patch({x:50,y:50,fit:'cover',size:100})}>{tr("Fill face")}</button><button onClick={()=>patch({x:50,y:50})}>{tr("Center")}</button></div>
 {selected.kind==='image'&&<><div className="placement-actions"><button disabled={busy} onClick={removeWhite}>{tr("Remove white background and trim")}</button>{originals[selected.id]&&<button onClick={()=>patch(originals[selected.id])}>{tr("Restore original background")}</button>}</div><small>{tr("Removes near-white background connected to the edges. Intended for white-background logos. Restore is available during this editing session.")}</small><label>{tr("Image fit")}<select aria-label="Image fit" value={selected.fit||'contain'} onChange={e=>patch({fit:e.target.value})}><option value="contain">{tr("Fit entire image (no crop)")}</option><option value="cover">{tr("Fill area (crop edges)")}</option><option value="width">{tr("Fit width (legacy)")}</option></select></label></>}
 {selected.kind==='text'&&<><label>{tr("Text color")}<input type="color" value={selected.color} onChange={e=>patch({color:e.target.value})}/></label></>}
 {defaultFinish!=='print'&&(selected.finish||'print')==='print'&&<button onClick={()=>patch({finish:defaultFinish})}>{tr("Apply recommended finish to this layer")}</button>}<label>{tr("Artwork finish (preview)")}<select aria-label="Artwork finish (preview)" value={selected.finish||'print'} onChange={e=>patch({finish:e.target.value})}><option value="print">{tr("Print")}</option><option disabled={box.category==='corrugated'} value="gold">{tr("Gold foil")}</option><option disabled={box.category==='corrugated'} value="silver">{tr("Silver foil")}</option><option disabled={['corrugated','bag'].includes(box.category)} value="uv">{tr("Spot UV")}</option><option disabled={box.category==='corrugated'} value="emboss">{tr("Emboss (visual only)")}</option></select></label><small>{tr("Foil works best with a transparent logo. An opaque background will also receive the effect. Use Print for ordinary images, and confirm the finish mask before production.")}</small>
 {selected.kind==='image'&&<><label><input type="checkbox" checked={selected.whiteBackground===false} onChange={e=>patch({whiteBackground:!e.target.checked})}/>{tr("Background matches the intended design")}</label>{selected.finish!=='print'&&<label><input type="checkbox" checked={!!selected.maskConfirmed} onChange={e=>patch({maskConfirmed:e.target.checked})}/>{tr("This transparent artwork is the separate finish mask")}</label>}</>}<button onClick={()=>patch({x:50,y:50,size:70,fit:'contain'})}>{tr("Reset position")}</button><details><summary>{tr("Fine-tune position and layers")}</summary><label>{tr("Horizontal position")}<input type="range" min="0" max="100" value={selected.x} onChange={e=>patch({x:Number(e.target.value)})}/></label><label>{tr("Vertical position")}<input type="range" min="0" max="100" value={selected.y} onChange={e=>patch({y:Number(e.target.value)})}/></label><button onClick={()=>onChange([...artworks.filter(a=>a.id!==selected.id),selected])}>{tr("Bring to front")}</button></details>
 <label>{tr("Size")}<input type="range" min="8" max="100" value={selected.size} onChange={e=>patch({size:Number(e.target.value)})}/></label><button className="remove-art" onClick={()=>onChange(artworks.filter(a=>a.id!==selected.id))}>{tr("Delete selected layer")}</button></fieldset>
 </div>}</>}
 </section><StructurePreview startIn3d box={box} artworks={artworks} visualOptions={visualOptions} onVisualChange={onVisualChange}/></div>
}
