import studioLogo from '../../../public/brand/mtt-gold-triangle.webp';
import {useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import DesignStudio from './components/DesignStudio';
import GiftBoxPreview from './components/GiftBoxPreview';
import BoxThumbnail from './components/BoxThumbnail';
import PackagingSet from './components/PackagingSet';
import {buildBox} from './lib/packaging.mjs';
import {STRUCTURES,MATERIALS,FINISHES,INSERTS,DISCLAIMER,sanitizeProject,parsePublicProject,exportPublicProject,preflight,historyPush,historyUndo,historyRedo} from './lib/solution-project.mjs';
import {leadPayload,sendLead,whatsappURL,publicBrief,validateLead} from './lib/solution-lead.mjs';
import {AXES,FACTORS,DESIGN_HANDOFF_KEY,dimensionText,displayNumber,draftFromProject,planSize,projectFromCalculator,validDimensions} from './lib/size-plan.mjs';

type Project=ReturnType<typeof sanitizeProject>;
const STORE='mtt-public-solution-projects-v1', ACTIVE='mtt-public-solution-active';
const STEPS=['Structure','Size','Design','Quote'];
const FAMILIES=[['all','All structures'],['rigid','Rigid boxes'],['carton','Folding cartons'],['corrugated','Corrugated'],['bag','Paper bags']];
const NOTES:Record<string,string>={tianlide:'Separate lid. A considered first impression.',drawer:'A sliding reveal for small, treasured products.',flip:'A hinged lid for a complete presentation.',book:'A book-style opening with a defined spine.',foldable_flip:'A collapsible direction to review for shipping.',window_flip:'A viewing window for product visibility.',double_door:'Two doors for a central product reveal.',shoulder:'A raised neck between the base and lid.',airplane:'A roll-end mailer for direct-to-customer delivery.',rsc:'A shipping carton for secondary protection.',tuck:'A compact paperboard carton for retail.',paperbag:'A carry bag with a side gusset.'};
function stored():Project[]{try{const a=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(a)?a.flatMap(p=>{try{return[sanitizeProject(p)]}catch{return[]}}):[]}catch{return[]}}
function fresh(){return sanitizeProject({type:'tianlide',name:'Untitled packaging project',solutionId:'custom',dimensions:{length:190,width:130,height:60},product:{name:'',dimensions:{length:180,width:120,height:50},quantity:500},sizePlan:{mode:'product',unit:'mm',clearanceMm:5},visualOptions:{paperColor:'#eee5cf',surface:'matte',opening:55}})}
function initial(){try{return stored().find(p=>p.id===localStorage.getItem(ACTIVE))||fresh()}catch{return fresh()}}
function download(name:string,body:string,mime='text/html;charset=utf-8'){const url=URL.createObjectURL(new Blob([body],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function track(event:string){if(window.parent!==window)window.parent.postMessage({source:'mtt-gift-builder',event},location.origin)}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();window.scrollTo({top:0});if(window.parent!==window)window.parent.postMessage({source:'mtt-gift-builder',event:'step'},location.origin)},[]);return <dialog ref={ref} className="studio-modal" onCancel={onClose}><div className="modal-heading"><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Close dialog">Close</button></div>{children}</dialog>}
export default function StudioApp(){
 const [history,setHistory]=useState(()=>({past:[] as Project[],present:initial(),future:[] as Project[]}));
 const project=history.present;
 const [step,setStep]=useState(0),[family,setFamily]=useState('all'),[draft,setDraft]=useState(()=>draftFromProject(project));
 const [notice,setNotice]=useState(''),[saveStatus,setSaveStatus]=useState(''),[libraryOpen,setLibraryOpen]=useState(false),[incoming,setIncoming]=useState<Project|null>(null),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[sendError,setSendError]=useState(''),[draftDirty,setDraftDirty]=useState(false);
 const pending=useRef(false), touched=useRef(false), started=useRef(false), sendLock=useRef('');
 const [contact,setContact]=useState({customer_name:'',email:'',company:'',country:'',whatsapp:'',artwork_url:'',customer_message:''});
 const box=useMemo(()=>buildBox(project.type,project.dimensions),[project.type,project.dimensions]);
 const sizeResult=planSize(draft,project.sizePlan.mode,project.sizePlan.unit), sizeError=sizeResult.error;
 const check=preflight(project), materials=MATERIALS.filter(m=>m.categories.includes(box.category));
 const unit=project.sizePlan.unit, mode=project.sizePlan.mode, unitLabel=unit==='inch'?'in':unit;
 const save=(p=project,explicit=false)=>{try{localStorage.setItem(STORE,JSON.stringify([sanitizeProject(p),...stored().filter(v=>v.id!==p.id)]));localStorage.setItem(ACTIVE,p.id);setSaveStatus('Saved on this device');if(explicit)setNotice('Project saved on this device. Export a project file to keep a separate copy.');return true}catch{setSaveStatus('Device storage is full or unavailable. Export your project to keep a copy.');return false}};
 function update(patch:any){if(pending.current)return;touched.current=true;setHistory(h=>{const next={...h.present,...(typeof patch==='function'?patch(h.present):patch),updatedAt:new Date().toISOString()};const pushed=historyPush(h,h.present,next);return {...pushed,past:pushed.past.slice(-40)}});setSent(false);setSendError('')}
 function load(p:Project){const next=sanitizeProject(p);touched.current=false;setHistory({past:[],present:next,future:[]});setDraft(draftFromProject(next));setDraftDirty(false);setStep(1);setSent(false);setSaveStatus('');setLibraryOpen(false);setNotice('Project opened. Review its dimensions before continuing.');}
 useEffect(()=>{if(!touched.current||sizeError)return;const timer=setTimeout(()=>save(),800);return()=>clearTimeout(timer)},[project,sizeError]);
 useEffect(()=>{try{const raw=sessionStorage.getItem(DESIGN_HANDOFF_KEY);if(raw){const p=projectFromCalculator(JSON.parse(raw));setIncoming(sanitizeProject({...p,id:crypto.randomUUID(),name:'Calculator project'}));}}catch(e){setNotice(`Calculator data could not be loaded. ${(e as Error).message}`)}},[]);
 useEffect(()=>{if(window.parent===window)return;let timer:number;const report=()=>{cancelAnimationFrame(timer);timer=requestAnimationFrame(()=>window.parent.postMessage({source:'mtt-gift-builder',event:'resize',height:Math.ceil(document.documentElement.getBoundingClientRect().height)},location.origin))};const observer=new ResizeObserver(report);observer.observe(document.body);report();return()=>{observer.disconnect();cancelAnimationFrame(timer)}},[]);
 function go(next:number){if(pending.current)return;if(next>=2&&sizeError){setNotice('Complete the size fields before moving on.');setStep(1);return}if(!started.current){track('gift_builder_start');started.current=true}if(next===3)track('gift_builder_design_completed');setStep(next);setNotice('');window.scrollTo({top:0,behavior:'smooth'});if(window.parent!==window)window.parent.postMessage({source:'mtt-gift-builder',event:'step'},location.origin)}
 function choose(type:string){const category=buildBox(type,project.dimensions).category,material=MATERIALS.find(m=>m.categories.includes(category));update({type,solutionId:'custom',materialId:material.id,boardMaterial:category==='rigid'?'Greyboard — thickness to be reviewed':material.name,wrappingMaterial:category==='rigid'?material.name:'None / direct print',printMethod:category==='corrugated'?'flexo':'offset'});track('gift_builder_solution_selected');go(1)}
 function editSize(key:string,value:string){const next={...draft,[key]:value};setDraft(next);setDraftDirty(true);const result=planSize(next,mode,unit);if(!result.error){setSaveStatus('Saving…');update({dimensions:result.dimensions,sizePlan:{...project.sizePlan,clearanceMm:mode==='product'?result.clearanceMm:project.sizePlan.clearanceMm},...(result.productDimensions?{product:{...project.product,dimensions:result.productDimensions}}:{})});}else{setSent(false);setSaveStatus('Complete the size fields to save your changes.')}}
 function changeUnit(next:string){if(sizeError){setNotice('Finish the current dimensions before changing units.');return}const plan={...project.sizePlan,unit:next};setDraft(draftFromProject({...project,sizePlan:plan}));update({sizePlan:plan});}
 function changeMode(next:string){const plan={...project.sizePlan,mode:next};let nextDraft=draftFromProject({...project,sizePlan:plan});if(next==='product'&&!validDimensions(project.product.dimensions))nextDraft={...nextDraft,length:'',width:'',height:''};setDraft(nextDraft);const result=planSize(nextDraft,next,unit);update({sizePlan:plan,...(!result.error?{dimensions:result.dimensions}:{})});setDraftDirty(true)}
 function undo(redo=false){const next=redo?historyRedo(history):historyUndo(history);setHistory(next);setDraft(draftFromProject(next.present));setDraftDirty(false);setSent(false);touched.current=true}
 function changeMaterial(id:string){const material=MATERIALS.find(m=>m.id===id);update({materialId:id,boardMaterial:box.category==='rigid'?'Greyboard — thickness to be reviewed':material.name,wrappingMaterial:box.category==='rigid'?material.name:'None / direct print'})}
 function artworkChange(artworks:any[]){const crafts=[...project.crafts];for(const [finish,id] of [['gold','foil'],['silver','foil'],['uv','spot-uv'],['emboss','emboss']])if(artworks.some(a=>a.finish===finish)&&!crafts.includes(id))crafts.push(id);update({artworks,crafts})}
 function brief(){let preview='';window.dispatchEvent(new CustomEvent('mtt-capture-preview',{detail:{receive:(url:string)=>{preview=url}}}));download(`MTT-${project.id}-brief.html`,publicBrief(project,preview));if(!preview)setNotice('Brief downloaded. Open the 3D preview to include an image in your next export.')}
 async function importProject(file?:File){if(!file)return;try{if(file.size>12000000)throw Error('Project exceeds 12 MB.');const imported=parsePublicProject(await file.text());const existing=stored().find(p=>p.id===imported.id);setIncoming(existing?{...imported,id:crypto.randomUUID(),name:`${imported.name} (imported copy)`}:imported);setLibraryOpen(false)}catch(e){setNotice((e as Error).message)}}
 async function submit(e:React.FormEvent){e.preventDefault();if(pending.current)return;const errors=[...(sizeError?[sizeError]:[]),...validateLead(project,contact)];if(errors.length){setSendError(errors.join(' '));return}const payload=leadPayload(project,contact),signature=JSON.stringify(payload);if(sendLock.current===signature){setSent(true);return}pending.current=true;setBusy(true);setSendError('');try{await sendLead(payload);sendLock.current=signature;setSent(true);track('gift_builder_email_submit')}catch(e){setSendError((e as Error).message)}finally{pending.current=false;setBusy(false)}}
 const sizeNames=project.type==='paperbag'?['Bag width','Gusset','Bag height']:['Box length','Box width','Box height'];
 const MaterialPanel=<details className="studio-materials"><summary>Materials, finishes & inserts</summary><label>Paper / board<select value={project.materialId} onChange={e=>changeMaterial(e.target.value)}>{materials.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Insert direction<select value={project.insert} onChange={e=>update({insert:e.target.value})}>{Object.entries(INSERTS).map(([id,v]:any)=><option key={id} value={id}>{v.name}</option>)}</select></label><div className="studio-finish-list">{FINISHES.map(f=><label key={f.id}><input type="checkbox" checked={project.crafts.includes(f.id)} onChange={e=>update({crafts:e.target.checked?[...project.crafts.filter(id=>!(f.id==='matte-film'&&id==='gloss-film'||f.id==='gloss-film'&&id==='matte-film')),f.id]:project.crafts.filter(id=>id!==f.id)})}/>{f.name}</label>)}</div><p className="microcopy">Material grades, caliper and finish compatibility are reviewed before quoting.</p></details>;
 return <div className="packaging-studio">
  <header className="studio-header"><a href="/" target="_top" className="studio-brand"><img src={studioLogo} alt="MTT" width="56" height="50"/><span>MTT PACKAGING</span></a><span className="studio-wordmark">PACKAGING STUDIO</span><div className="studio-header-actions"><button disabled={busy||!!sizeError} onClick={()=>save(project,true)}>Save project</button><button disabled={busy} onClick={()=>setLibraryOpen(true)}>My projects</button><button disabled={busy} onClick={()=>go(3)}>Contact Hugo</button></div></header>
  <nav aria-label="Packaging design steps" className="studio-steps">{STEPS.map((name,i)=><button key={name} disabled={busy} aria-current={step===i?'step':undefined} onClick={()=>go(i)} className={`${step===i?'current':''} ${i<step?'complete':''}`}><span>{i<step?'✓':i+1}</span>{name}</button>)}</nav>
  {notice&&<div className="studio-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notice">×</button></div>}
  <fieldset disabled={busy} className="studio-body">
  {step===0&&<section className="structure-section"><div className="structure-intro"><div><p className="eyebrow">01 / CHOOSE YOUR STRUCTURE</p><h1>A good fit starts here.</h1><p>Choose an opening style. Then size it around your product and make it your own.</p></div><button className="text-button" onClick={()=>go(3)}>Need a custom structure? Ask Hugo →</button></div><div className="family-tabs" role="group" aria-label="Structure family">{FAMILIES.map(([id,label])=><button aria-pressed={family===id} className={family===id?'selected':''} onClick={()=>setFamily(id)} key={id}>{label}</button>)}</div><div className="structure-grid">{Object.entries(STRUCTURES).filter(([type])=>family==='all'||buildBox(type,project.dimensions).category===family).map(([type,title]:any)=><button className={`structure-tile ${type===project.type?'chosen':''}`} key={type} onClick={()=>choose(type)}><BoxThumbnail type={type} decorative/><span className="structure-title">{title}<span aria-hidden="true">↗</span></span><small>{NOTES[type]}</small><span className="tile-link">Choose & size →</span></button>)}</div><p className="microcopy">Illustrative structures. MTT reviews material, fit and manufacturing feasibility with you.</p></section>}
  {step===1&&<section className="size-workspace">
   <div className="size-stage"><div className="stage-heading"><h1>Sized for your product.</h1><p>{STRUCTURES[project.type]} · <button onClick={()=>go(0)}>Change</button></p></div>{!sizeError?<GiftBoxPreview key={project.type} type={project.type} dimensions={project.dimensions} artworks={project.artworks} options={project.visualOptions} onChange={visualOptions=>update({visualOptions})} studioStage/>:<div className="preview-placeholder"><p>Enter your dimensions to see the planned proportions.</p></div>}<div className="stage-dimensions" aria-live="polite"><strong>{sizeError?'Dimensions incomplete':dimensionText(project.dimensions)}</strong><span>Planned internal dimensions · illustrative preview</span>{project.type==='paperbag'&&<small>Bag width × gusset × height</small>}</div></div>
   <div className="size-panel"><p className="eyebrow">02 / PLAN YOUR SIZE</p><h2>What are you packing?</h2><div className="segmented" role="group" aria-label="Dimension basis"><button className={mode==='product'?'selected':''} aria-pressed={mode==='product'} onClick={()=>changeMode('product')}>Product dimensions</button><button className={mode==='box'?'selected':''} aria-pressed={mode==='box'} onClick={()=>changeMode('box')}>Box dimensions</button></div><div className="segmented units" role="group" aria-label="Dimension unit">{Object.keys(FACTORS).map(u=><button key={u} aria-pressed={unit===u} className={unit===u?'selected':''} onClick={()=>changeUnit(u)}>{u==='inch'?'in':u}</button>)}</div>
   <div className="dimension-fields">{AXES.map((key,i)=><label className="dimension-row" key={key}><span>{mode==='product'?`Product ${key}`:sizeNames[i]}</span><span className="dimension-input"><input type="number" inputMode="decimal" step="any" min="0" aria-label={mode==='product'?`Product ${key}`:sizeNames[i]} value={draft[key]} aria-invalid={!!sizeError} onChange={e=>editSize(key,e.target.value)}/><span>{unitLabel}</span></span></label>)}</div>
   {mode==='product'?<div className="clearance-field"><label className="dimension-row"><span>Clearance per side</span><span className="dimension-input"><input type="number" inputMode="decimal" min="0" step="any" aria-label="Clearance per side" value={draft.clearance} onChange={e=>editSize('clearance',e.target.value)}/><span>{unitLabel}</span></span></label><p className="microcopy">Example allowance, not a factory standard. Adjust for inserts and protection.</p></div>:<p className="microcopy box-size-note">Enter the usable <strong>inside</strong> size. External dimensions depend on the structure, board and assembly. Product fit is still to be reviewed.</p>}
   {sizeError?<p className="field-error" role="alert">{sizeError}</p>:<div className="size-formula"><span>{mode==='product'?'Inside size = product + clearance on both sides':'Customer-specified internal size'}</span>{mode==='product'&&<small>{AXES.map(k=>`${displayNumber(project.product.dimensions[k])} + (${displayNumber(project.sizePlan.clearanceMm)} × 2)`).join('   /   ')} mm</small>}<strong>= {dimensionText(project.dimensions)}</strong></div>}
   <button className="primary wide" disabled={!!sizeError} onClick={()=>go(2)}>Continue to design →</button><button className="sizing-help" onClick={()=>{setContact(c=>({...c,customer_message:c.customer_message||'Please help me review the dimensions and product fit.'}));go(3)}}>I need help with sizing</button>{!draftDirty&&!project.product.name&&project.name==='Untitled packaging project'&&<p className="microcopy starting-note">Starting example — replace with your measurements.</p>}</div>
  </section>}
  {step===2&&<section className="design-section"><div className="design-intro"><div><p className="eyebrow">03 / MAKE IT YOURS</p><h1>Your brand. In the details.</h1><p>{STRUCTURES[project.type]} · {dimensionText(project.dimensions)} inside · <button className="text-button" onClick={()=>go(1)}>Edit size</button></p></div><div className="design-actions"><button disabled={!history.past.length} onClick={()=>undo()}>Undo</button><button disabled={!history.future.length} onClick={()=>undo(true)}>Redo</button><button className="primary" onClick={()=>go(3)}>Review & request a quote →</button></div></div><DesignStudio box={box} artworks={project.artworks} onChange={artworkChange} visualOptions={project.visualOptions} onVisualChange={visualOptions=>update({visualOptions})} onUploadIssue={rawUnsupported=>update({rawUnsupported})} settingsPanel={MaterialPanel}/><details className="studio-set"><summary>Add a matching bag, shipping carton or packaging set</summary><PackagingSet project={project} onChange={accessories=>update({accessories})}/></details></section>}
  {step===3&&<section className="quote-workspace"><div className="quote-overview"><p className="eyebrow">04 / YOUR PACKAGING BRIEF</p><h1>Let’s make it work.</h1><p>Send Hugo your direction. We’ll review the fit, materials and artwork before preparing a formal quote.</p><GiftBoxPreview key={project.type} type={project.type} dimensions={project.dimensions} artworks={project.artworks} options={project.visualOptions} onChange={visualOptions=>update({visualOptions})}/><dl className="quote-specs"><div><dt>Structure</dt><dd>{STRUCTURES[project.type]} <button onClick={()=>go(0)}>Edit</button></dd></div><div><dt>Planned internal size</dt><dd>{dimensionText(project.dimensions)} <button onClick={()=>go(1)}>Edit</button>{project.type==='paperbag'&&<small>Bag width × gusset × height</small>}</dd></div><div><dt>Size basis</dt><dd>{mode==='product'?`Product + ${displayNumber(project.sizePlan.clearanceMm)} mm allowance per side`:'Known internal dimensions. Product fit not verified.'}</dd></div><div><dt>Material / insert</dt><dd>{project.boardMaterial} / {INSERTS[project.insert].name}</dd></div><div><dt>Finishes</dt><dd>{project.crafts.map(id=>FINISHES.find(f=>f.id===id)?.name).join(', ')||'None selected'}</dd></div><div><dt>Artwork</dt><dd>{project.artworks.length} layer(s) <button onClick={()=>go(2)}>Edit</button></dd></div></dl><div className="export-actions"><button onClick={brief}>Download brief</button><button onClick={()=>download(`MTT-${project.id}.json`,exportPublicProject(project),'application/json')}>Export editable project</button></div><details className="preflight"><summary>Project checks · {check.issues.length} item(s) to review</summary>{check.issues.length?<ul>{check.issues.map((i,index)=><li key={index}>{i.severity}: {i.message}</li>)}</ul>:<p>No issues detected by local checks. Engineering review is still required.</p>}<p className="microcopy">Artwork edge and resolution checks use configurable project assumptions, not production approval.</p></details></div>
   <form className="quote-form" onSubmit={submit} noValidate><h2>Talk through your project.</h2><p className="microcopy">Your specification is included automatically.</p><label>Product / project name<input aria-label="Product name" maxLength={120} value={project.product.name} placeholder="e.g. A 50 ml fragrance launch" onChange={e=>update({name:e.target.value||'Untitled packaging project',product:{...project.product,name:e.target.value}})}/></label><label>Planned quantity<input aria-label="Planned quantity" type="number" inputMode="numeric" min="1" max="1000000" value={project.product.quantity||''} onChange={e=>update({product:{...project.product,quantity:Number(e.target.value)}})}/><small>MOQ and production feasibility will be confirmed after review.</small></label><div className="contact-grid">{[['customer_name','Your name'],['email','Business email'],['company','Company'],['country','Delivery country']].map(([key,label])=><label key={key}>{label}<input required autoComplete={({customer_name:'name',email:'email',company:'organization',country:'country-name'})[key]} type={key==='email'?'email':'text'} maxLength={key==='email'?254:150} value={(contact as any)[key]} onChange={e=>{setContact({...contact,[key]:e.target.value});setSent(false)}}/></label>)}</div><label>Artwork sharing link <span>(optional)</span><input type="url" placeholder="https://…" maxLength={2000} value={contact.artwork_url} onChange={e=>setContact({...contact,artwork_url:e.target.value})}/></label><label>What should we know?<textarea rows={4} maxLength={3000} placeholder="Product protection, delivery timing, target quantity or a special opening…" value={contact.customer_message} onChange={e=>setContact({...contact,customer_message:e.target.value})}/></label><p className="microcopy">Uploaded artwork stays in this browser. Share an artwork link or send your exported project separately. Sending this form shares your contact details and packaging specification with MTT.</p>{sendError&&<p className="field-error" role="alert">{sendError}</p>}{sent?<div className="success-message" role="status"><strong>Your brief was accepted.</strong><p>Hugo will review the specification and contact you. This is not a confirmed production order.</p></div>:<button className="primary wide" type="submit" disabled={busy||!!sizeError}>{busy?'Sending your brief…':'Send my brief to Hugo →'}</button>}<a className="whatsapp-button" href={whatsappURL(project)} target="_blank" rel="noopener noreferrer" onClick={()=>track('gift_builder_whatsapp_click')}>Or discuss this specification on WhatsApp ↗</a><p className="microcopy">WhatsApp opens a draft with the dimensions and finishes. Review it before sending; images are not attached automatically.</p></form>
  </section>}
  </fieldset>
  <footer className="studio-footer"><span>Your structure, size and design travel together in one quote request.</span><span>Reviewed by Hugo before quoting.</span></footer><div className="studio-save-status" role="status">{saveStatus}</div>
  {libraryOpen&&<Modal title="Your packaging projects" onClose={()=>setLibraryOpen(false)}><p>Saved locally on this device. Export a project for a portable backup.</p><button className="primary" onClick={()=>{save();load(fresh())}}>Start a new project</button><label className="import-file">Import a project file<input type="file" accept="application/json,.json" onChange={e=>{importProject(e.target.files?.[0]);e.target.value=''}}/></label><div className="project-list">{stored().map(p=><button key={p.id} onClick={()=>load(p)}><strong>{p.name}</strong><span>{STRUCTURES[p.type]} · {dimensionText(p.dimensions)}</span></button>)}{!stored().length&&<p>No saved projects yet.</p>}</div><button onClick={()=>download(`MTT-${project.id}.json`,exportPublicProject(project),'application/json')}>Export current project</button></Modal>}
  {incoming&&<Modal title="Open these dimensions?" onClose={()=>{setIncoming(null);try{sessionStorage.removeItem(DESIGN_HANDOFF_KEY)}catch{}}}><p>{STRUCTURES[incoming.type]} · {dimensionText(incoming.dimensions)} internal</p><p>This opens a separate project. Your currently saved projects remain available under My projects.</p><button className="primary" onClick={()=>{save();const p=incoming;setIncoming(null);try{sessionStorage.removeItem(DESIGN_HANDOFF_KEY)}catch{}load(p);save(p)}}>Open as a new project</button><button onClick={()=>{setIncoming(null);try{sessionStorage.removeItem(DESIGN_HANDOFF_KEY)}catch{}}}>Keep current project</button></Modal>}
 </div>
}
