import {products} from '../lib/products';
import type { MetadataRoute } from 'next';
import { articles } from '../lib/articles';
import { industries } from '../lib/industries';
import { siteUrl } from '../lib/seo';
const updatedProducts = new Set(products.flatMap(p=>['products/'+p.slug,'zh/products/'+p.slug]));
export const dynamic = 'force-static';
export default function sitemap(): MetadataRoute.Sitemap {
  const paths = ['products','zh/products',...products.flatMap(p=>['products/'+p.slug,'zh/products/'+p.slug]),'zh','zh/request-a-quote','', 'packaging', 'industries', 'how-we-work', 'sustainability', 'case-studies', 'insights', 'request-a-quote', 'about', 'quality-control', 'ppwr-compliant-packaging', 'privacy-policy', 'cookie-policy', 'tools', 'tools/box-size-calculator', 'tools/gift-box-solution-builder', ...['custom-rigid-boxes', 'corrugated-boxes', 'folding-cartons', 'custom-paper-bags', 'custom-inserts'].map(s => `packaging/${s}`), ...industries.map(i => `industries/${i.slug}`)];
  return [...paths.map(path => ({ url: path ? `${siteUrl}/${path}` : siteUrl, ...(path === 'insights' ? {lastModified:'2026-10-08'} : ['industries/cosmetics-skincare-packaging','industries/perfume-fragrance-packaging'].includes(path) ? {lastModified:'2026-10-04'} : (['industries/jewelry-watch-packaging','industries/gift-set-pr-kit-packaging',...['anniversary-ring-pair-lift-off','boutique-accessory-gift-shoulder'].flatMap(slug=>['products/'+slug,'zh/products/'+slug])].includes(path)) ? {lastModified:'2026-09-30'} : (path.startsWith('industries/') || ['packaging/custom-rigid-boxes','packaging/folding-cartons', ...['signature-perfume-lift-off','skincare-ritual-collapsible-magnetic-rigid-box','custom-wrapped-mooncakes-window-tuck'].flatMap(slug=>['products/'+slug,'zh/products/'+slug])].includes(path)) ? {lastModified:'2026-09-29'} : ['sustainability','how-we-work','industries','industries/cosmetics-skincare-packaging','products/skincare-ritual-collapsible-magnetic-rigid-box','zh/products/skincare-ritual-collapsible-magnetic-rigid-box'].includes(path) ? {lastModified:'2026-09-28'} : ['products','zh/products','packaging/folding-cartons'].includes(path) ? {lastModified:'2026-09-15'} : updatedProducts.has(path) ? {lastModified:'2026-09-17'} : ['request-a-quote','zh/request-a-quote','products','insights','packaging/folding-cartons','packaging/corrugated-boxes','packaging/custom-paper-bags'].includes(path) ? {lastModified:'2026-09-14'} : ['packaging/custom-rigid-boxes','packaging/custom-inserts','industries/perfume-fragrance-packaging','tools/gift-box-solution-builder'].includes(path) ? {lastModified:path==='industries/perfume-fragrance-packaging'?'2026-09-12':'2026-09-10'} : {}) })), ...articles.map(article => ({ url: `${siteUrl}/insights/${article.slug}`, lastModified: article.dateModified || article.datePublished }))];
}
