import type {Metadata} from 'next';
import GiftBuilderFrame from '../../../components/GiftBuilderFrame';
const url='https://mttpackaging.com/tools/gift-box-solution-builder';
export const metadata:Metadata={title:'Design Your Box: Size, Preview & Quote | MTT Packaging',description:'Plan internal box dimensions, choose your packaging structure and preview your artwork. Send a complete custom packaging brief to Hugo for engineering review.',alternates:{canonical:url},openGraph:{title:'MTT Packaging Studio — Design Your Box',description:'From product dimensions to a custom packaging brief.',url}};
export default function GiftBuilderPage(){return <main id="main-content" className="studio-page" style={{margin:0,padding:0,maxWidth:'none'}}><h1 style={{position:'absolute',width:1,height:1,padding:0,overflow:'hidden',clipPath:'inset(50%)'}}>Design Your Box — MTT Packaging Studio</h1><style>{`body:has(.studio-page) .hugo-widget{display:none}
.studio-help{padding:0 5%;border-top:1px solid #d6d9ce;font-size:14px;background:#f7f6f1}
.studio-help summary{cursor:pointer;padding:17px 0;font-weight:600;line-height:1.4;min-height:52px}
.studio-help summary:focus-visible{outline:2px solid #9b7941;outline-offset:3px}
.studio-help-content{max-width:1180;margin:0 auto;padding:4px 0 22px;line-height:1.65}
.studio-help h2{font:400 27px/1.2 Georgia,serif;margin:0 0 12px}
.studio-help h3{font-size:16px;font-weight:600;margin:0 0 8px}
.studio-help p{margin:0 0 14px}.studio-help a{text-decoration:underline;text-underline-offset:3px}
.studio-guidance{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:24px;margin:20px 0 4px}
@media(max-width:600px){.studio-help{padding:0 6%}.studio-guidance{gap:12px}.studio-help h2{font-size:23px}}`}</style><GiftBuilderFrame/><details className="studio-help"><summary>Size & design guidance</summary><div className="studio-help-content"><h2>From your product dimensions to a packaging brief.</h2><p>Start with the product length, width and height, or enter a known internal box size. Use millimetres, centimetres or inches. The studio carries your dimensions, structure, material direction and artwork choices into one specification for MTT to review.</p><div className="studio-guidance"><article><h3>What does the size calculation mean?</h3><p>For each axis, planned internal size equals product size plus the allowance on both sides. A 180 × 120 × 50 mm product with an illustrative 5 mm allowance per side gives 190 × 130 × 60 mm inside. The allowance is editable; it is not a universal tolerance. Inserts, product variation and assembly change what you need.</p></article><article><h3>Which dimensions should you send?</h3><p>For boxes, use finished internal length × width × height. For paper bags, use width × gusset × height. The studio does not convert internal dimensions into a production-ready external size: board caliper, wrapping, folds and closures require structural review.</p></article><article><h3>What happens after the design?</h3><p>Send your planned quantity, delivery country and specification to Hugo. MTT reviews material suitability, protection, artwork and sampling requirements before a formal quote. Preview colours and finishes are illustrative. A physical sample and approved dieline establish the production specification.</p></article></div><p>Continue planning with the <a href="/tools/box-size-calculator">box size, sheet layout and shipping-volume calculator</a>, explore <a href="/packaging/custom-rigid-boxes">custom rigid boxes</a> or discuss a <a href="/request-a-quote">custom structure with MTT</a>.</p></div></details></main>}
