export const articles = [
  { slug: 'custom-box-structure-guide', number: '01', angle: 'Structure', image: '/structure/structure-1.webp', imageAlt: 'Magnetic book-style premium rigid box structure', title: 'How to Choose the Right Custom Box Structure', summary: 'Compare rigid, folding carton, drawer, magnetic and corrugated structures by presentation, protection, volume and production needs.', intro: 'The right box structure is a commercial decision as much as a visual one. It affects tooling, assembly, packing speed, shipping volume, protection and the way a customer first handles the product.', datePublished: '2026-08-15', dateModified: '2026-08-28', faq: [['What is the most common structure for luxury packaging?', 'Rigid boxes—particularly magnetic and lift-off lid structures—are the most common choice for luxury packaging because they offer strong visual impact, a controlled opening experience and reliable product protection.'], ['When should I choose a folding carton over a rigid box?', 'Folding cartons suit high-volume retail products where storage efficiency and freight cost matter. Rigid boxes suit lower-volume gifting, launches and premium presentation where the box itself is part of the brand experience.']], sections: [
    ['Start with the product and sales channel', 'Confirm finished internal dimensions in L × W × H, product weight, fragility, retail or e-commerce use, order quantity and destination. A premium retail launch may justify a rigid presentation box, while a high-volume product may need a folding carton or corrugated mailer.'],
    ['Common premium structures', 'Magnetic book-style rigid boxes create a strong reveal. Drawer boxes offer a controlled slide-out experience. Lift-off lid boxes are versatile and efficient to pack. Folding cartons reduce storage and freight volume. Corrugated structures add transport protection and can still carry premium printing.'],
    ['Balance presentation and logistics', 'A beautiful box that ships mostly empty space can increase total landed cost. Fold-flat constructions, removable inserts and optimized outer cartons may reduce storage and freight, but savings should be confirmed with packed dimensions, carton count, CBM and weight.'],
    ['What to confirm before sampling', 'Approve the exact structure name, internal size, board thickness, opening direction, closure, insert concept, print areas and intended packing method before producing a physical sample.'],
  ]},
  { slug: 'packaging-material-selection', number: '02', angle: 'Materials', image: '/sustainability/documented-sourcing.webp', imageAlt: 'Premium paper and board material samples', title: 'Packaging Material Selection for Premium Boxes', summary: 'Understand greyboard, paperboard, corrugated board, specialty paper and responsible material options without over-specifying cost.', intro: 'Material selection determines stiffness, print behavior, edge quality, weight and tactile character. The most expensive substrate is not automatically the most suitable one.', datePublished: '2026-08-15', dateModified: '2026-08-28', faq: [['What is greyboard and why is it used for rigid boxes?', 'Greyboard is a dense, recycled paperboard typically used as the structural core of rigid boxes. It provides stiffness, weight and a premium feel at a lower cost than virgin fibre board, and accepts wrapping papers for a finished exterior.'], ['Can I request FSC-certified materials for my packaging?', 'Yes. FSC-certified papers and boards are available for most structures. The certificate applies to specific material grades and suppliers, so the claim should be confirmed against the actual material specification for your project.']], sections: [
    ['Structural board', 'Rigid boxes commonly use greyboard selected by thickness and density. Folding cartons use paperboard chosen by caliper, stiffness and print surface. Corrugated packaging adds flute selection, compression strength and edge-crush considerations.'],
    ['Wrapping and face paper', 'Coated paper supports detailed offset printing and lamination. Uncoated and textured specialty papers create a more tactile, restrained appearance but may change color reproduction, foil performance and rub resistance.'],
    ['Liners and exposed edges', 'Inside liners affect opening feel, cleanliness and brand color continuity. Wrapped edges, corner construction and paper grain direction influence the finished appearance of premium rigid boxes.'],
    ['Responsible choices', 'FSC-certified papers, recycled content, molded pulp and paper-based inserts can reduce plastic use. Claims should match actual certificates and the complete material specification rather than relying on a generic eco label.'],
  ]},
  { slug: 'printing-finishing-guide', number: '03', angle: 'Print & Finish', image: '/capability-folding-cartons.webp', imageAlt: 'Premium cartons with refined print and finishing', title: 'Printing and Finishing for Luxury Packaging', summary: 'Use color, foil, embossing, debossing, spot UV and texture with production tolerances and brand consistency in mind.', intro: 'Finishing should reinforce hierarchy and touch, not simply add decoration. Every process introduces cost, setup requirements and production tolerances that should be considered during artwork development.', datePublished: '2026-08-16', dateModified: '2026-08-28', faq: [['What is the difference between foil stamping and embossing?', 'Foil stamping applies a metallic or pigment layer to the surface using heat and pressure, creating shine or color. Embossing raises the surface physically to create a three-dimensional texture. Both can be combined for a foil-stamped and embossed logo.'], ['Does spot UV work on uncoated paper?', 'Spot UV can be applied to uncoated paper but the result may appear less glossy and more textured than on coated stock. A test proof is recommended to confirm the visual effect and adhesion on the specific paper.']], sections: [
    ['Color control', 'Specify Pantone or process color intent, the substrate, coating and approved reference. The same ink can appear different on coated paper, uncoated paper and colored specialty stock. Physical proofs remain important for critical brand colors.'],
    ['Foil stamping', 'Metallic, pigment and holographic foils create high contrast without ink. Fine lines, large solid areas, seams and textured paper require different tooling and pressure considerations.'],
    ['Embossing and debossing', 'Raised or recessed details add a tactile focal point. Artwork depth, board backing, register with print or foil and the reverse-side impression should be reviewed before tooling.'],
    ['Lamination, varnish and spot effects', 'Matte or gloss lamination changes color and rub resistance. Spot UV can create contrast but needs practical registration tolerance. Avoid combining processes only because they are available; prioritize the brand’s main visual signal.'],
  ]},
  { slug: 'custom-inserts-product-protection', number: '04', angle: 'Insert & Protection', image: '/sustainability/paper-based-options.webp', imageAlt: 'Molded pulp and paperboard custom inserts', title: 'Custom Inserts: Presentation, Fit and Product Protection', summary: 'Select paper, molded pulp, EVA or fabric-covered inserts based on fit, fragility, sustainability and the desired unboxing experience.', intro: 'An insert is part of the packaging structure. It controls movement, protects vulnerable areas and establishes how the product is presented when the box opens.', datePublished: '2026-08-17', dateModified: '2026-08-28', faq: [['What insert material is best for glass bottles?', 'The right insert depends on bottle weight, fragility, presentation and sustainability target. Molded pulp and paperboard platforms improve recyclability; EVA or fabric-covered foam provides tighter cushioning for heavier or more delicate bottles.'], ['Can one insert hold multiple products in a gift set?', 'Yes, but each product needs its own cavity dimensioned from measured product sizes—not from a photo or nominal fill volume. The lid clearance, finger access and product sequence should be planned before the insert is engineered.']], sections: [
    ['Begin with real product dimensions', 'Use measured product dimensions, weight, center of gravity, tolerances and fragile points. Nominal capacity or a product photo is not enough to engineer a secure fit.'],
    ['Paper and molded pulp', 'Folded paperboard inserts offer printability and recyclability. Molded pulp supports complex forms and plastic reduction, but tooling, surface texture and dimensional tolerance must suit the product.'],
    ['Foam and fabric-covered inserts', 'EVA and other foams provide cushioning and precise cavities. Fabric or paper wrapping improves presentation. Density, thickness, odor, color transfer and adhesive performance should be sampled.'],
    ['Test the complete pack', 'Evaluate insertion and removal, shake movement, compression, drop risk and the outer shipping carton—not only the insert on a desk. Final performance depends on the complete packaging system.'],
  ]},
  { slug: 'rigid-box-vs-folding-carton', number: '05', angle: 'How to choose', image: '/structure/structure-2.webp', imageAlt: 'Comparison of rigid box and folding carton structures', title: 'Rigid Box vs Folding Carton: Which Structure Fits Your Packaging Project?', summary: 'Compare rigid boxes and folding cartons on cost, MOQ, presentation, logistics and production to decide which structure suits your product and budget.', intro: 'Choosing between a rigid box and a folding carton is one of the first structural decisions in a packaging project. The right answer depends on product value, order quantity, distribution method, budget and the role the packaging plays in the brand experience.', datePublished: '2026-08-28', dateModified: '2026-08-28', faq: [['Is a rigid box always more expensive than a folding carton?', 'Generally yes—rigid boxes use more material, require hand assembly and cannot be shipped flat. However, at low volumes the price gap narrows because rigid box tooling costs are often lower than folding carton die costs.'], ['Can a folding carton look premium?', 'Yes. Specialty papers, foil stamping, embossing and high-quality printing can make a folding carton feel premium. The key difference is structural weight and the opening experience, not print quality.']], sections: [
    ['Understanding the structural difference', 'A rigid box is built from thick greyboard (typically 1.5–3 mm) wrapped with printed or specialty paper. It holds its shape, feels substantial and cannot be flattened. A folding carton is printed and die-cut from a single sheet of paperboard (typically 0.3–0.6 mm), then shipped flat and erected during packing. This fundamental difference drives cost, logistics and presentation.'],
    ['Cost comparison: what drives the price gap', 'Rigid boxes cost more per unit because they use heavier board, require separate wrapping, often need hand assembly and ship in larger cartons. Folding cartons are machine-made, ship flat and pack efficiently. However, at quantities under 1,000 pieces, rigid box tooling is often simpler and cheaper than a folding carton die with multiple folds and locks. The price crossover depends on the specific structure, finishes and order volume.'],
    ['When to choose a rigid box', 'Choose a rigid box when the packaging is part of the product experience—luxury gifting, product launches, influencer kits, retail displays where the customer handles the box before purchase, or products that need structural protection beyond what a carton provides. Magnetic closures, drawer mechanisms and shoulder-neck designs are only possible with rigid construction.'],
    ['When to choose a folding carton', 'Choose a folding carton for high-volume retail products, subscription boxes, individual units where storage and freight efficiency matter, or products where the packaging is functional rather than experiential. Folding cartons are also the better choice when shelf display requires hanging tabs or when the product needs to be visible through a window cutout.'],
    ['Hybrid approaches', 'Some projects use both: a rigid box for the gift set or launch edition, and a folding carton for the individual refill or retail unit. A shared colour palette, logo position and paper texture can connect the two structures visually while serving different distribution needs.'],
  ]},
  { slug: 'custom-packaging-cost-guide', number: '06', angle: 'Budget', image: '/structure/structure-3.webp', imageAlt: 'Custom packaging cost planning with material samples', title: 'Understanding Custom Packaging Costs: What Drives the Price', summary: 'Learn what factors determine the unit price of custom packaging—materials, printing, structure, finishes, order quantity and hidden costs most buyers overlook.', intro: 'Custom packaging pricing is not a single number. It is the result of material selection, structural complexity, printing and finishing processes, order quantity, tooling and logistics. Understanding these factors helps you write a better brief and avoid surprises.', datePublished: '2026-08-28', dateModified: '2026-08-28', faq: [['How much does a custom rigid box cost per unit?', 'The unit price depends on size, board thickness, wrapping paper, printing, finishes, insert material and order quantity. A simple rigid box with one-colour printing might start from $2–4 per unit at 1,000 pieces, while a complex multi-finish box with custom insert can reach $8–15 or more.'], ['What is the cheapest way to start with custom packaging?', 'The most cost-effective starting point is usually a simple structure with standard dimensions, one or two print colours, no foil or embossing, and a paperboard insert. This reduces tooling, setup and material costs while still delivering a branded experience.']], sections: [
    ['Materials: the foundation of cost', 'The substrate is the largest cost component. Greyboard for rigid boxes is priced by thickness and density. Paperboard for folding cartons varies by caliper, coating and specialty finish. Wrapping papers range from standard coated stock to textured uncoated papers and soft-touch laminates. Each step up in material quality adds cost, but also changes the tactile and visual result.'],
    ['Printing and finishing: where costs escalate', 'Each print colour requires a separate plate and setup pass. Foil stamping needs a custom die and heated press. Embossing and debossing each need their own tooling. Spot UV requires a screen or plate. Lamination adds a per-square-metre cost. A design that uses four print colours, foil, embossing and spot UV will cost significantly more than a one-colour print with a single finish—but may be exactly what the brand requires.'],
    ['Quantity and the unit price curve', 'Unit price drops as quantity rises because fixed costs (tooling, setup, sampling) are spread across more pieces. However, the relationship is not linear. A jump from 500 to 1,000 units often reduces unit price by 20–35%, while going from 5,000 to 10,000 might only save 8–15%. The sweet spot depends on the structure and your storage capacity.'],
    ['Hidden costs buyers often overlook', 'Beyond the box itself, budget for: physical sampling (often $150–500 per sample), artwork adaptation and prepress, insert tooling for molded pulp, export packing and carton costs, freight and import duties, and quality inspection. These are real project costs that should be in the brief from the start.'],
    ['How to write a cost-effective brief', 'Share your product dimensions, target quantity, desired structure, finish references, delivery country and target budget range. A clear budget range helps the packaging consultant recommend the right material, finish and quantity combination—rather than guessing and presenting options that overshoot or undershoot your needs.'],
  ]},
  { slug: 'packaging-materials-guide', number: '07', angle: 'Materials', image: '/sustainability/documented-sourcing.webp', imageAlt: 'Packaging material samples: greyboard, SBS, kraft and corrugated board', title: 'A Brand Guide to Packaging Materials: Greyboard, SBS, Kraft and Corrugated', summary: 'Understand the differences between greyboard, SBS paperboard, kraft paper and corrugated board—how each material performs, when to use it and what it costs.', intro: 'The material you choose determines how the box feels, how it prints, how it protects and how much it costs. This guide explains the four most common packaging substrates so you can make informed decisions in your brief.', datePublished: '2026-08-28', dateModified: '2026-08-28', faq: [['What is the difference between SBS and greyboard?', 'SBS (Solid Bleached Sulphate) is a white, clay-coated paperboard made from bleached virgin fibre—it prints cleanly and is used for folding cartons. Greyboard is a thick, dense recycled board used as the structural core of rigid boxes—it is not printed directly but wrapped with paper.'], ['Is kraft paper suitable for luxury packaging?', 'Kraft can work for luxury packaging when paired with the right brand positioning—natural, artisanal or eco-forward brands often use kraft for its texture and raw character. It prints well in one or two colours and takes foil and embossing effectively, though colour reproduction differs from coated white stock.']], sections: [
    ['Greyboard: the backbone of rigid boxes', 'Greyboard is a dense, multi-ply recycled paperboard made from recovered fibres. It comes in thicknesses from 1 mm to 3 mm and provides the structural stiffness that gives rigid boxes their weight and premium feel. Greyboard is not a finish surface—it is always wrapped with printed or specialty paper. Its main qualities are density, stiffness and cost efficiency. When specifying greyboard, confirm thickness, density (measured in g/cm³) and whether it meets any recycled content requirements.'],
    ['SBS paperboard: the folding carton standard', 'SBS (Solid Bleached Sulphate) is a white, clay-coated paperboard made from bleached virgin wood pulp. It offers a smooth, bright printing surface, good stiffness at lower calipers and clean fold performance. SBS is the standard choice for folding cartons in cosmetics, fragrance and premium retail. Common calipers range from 300 to 450 microns. The clay coating supports sharp offset printing, foil adhesion and lamination.'],
    ['Kraft board: natural character, growing demand', 'Kraft board is made from unbleached virgin or recycled fibres. It has a natural brown colour, visible fibre texture and a tactile, artisanal character. Kraft is popular with brands that want to signal naturalness, sustainability or a handcrafted aesthetic. It prints well in one or two colours, takes foil stamping and embossing effectively, but does not reproduce full-colour photography as cleanly as SBS. Kraft is available in both folding carton and corrugated grades.'],
    ['Corrugated board: protection with branding potential', 'Corrugated board combines a fluted inner layer with flat outer liners. The flute size (E, B, C or micro-flute) determines thickness, cushioning and print surface quality. E-flute and micro-flute corrugated are thin enough for high-quality printing and are used for e-commerce mailers, subscription boxes and shipping cartons that still carry brand identity. Corrugated adds transport protection that paperboard cannot match, but has a more utilitarian visual character.'],
    ['Choosing between them', 'Greyboard is for rigid boxes where weight and presentation matter. SBS is for folding cartons where print quality and shelf presence matter. Kraft is for brands where natural texture and eco positioning matter. Corrugated is for products that need transit protection with branded exterior. Many projects combine materials—a rigid box with SBS insert, a corrugated shipper with a kraft-lined interior. The right combination depends on product needs, brand positioning and budget.'],
  ]},
] as const;

export function getArticle(slug: string) { return articles.find((article) => article.slug === slug); }
