export const articles = [
  { slug: 'custom-box-structure-guide', number: '01', angle: 'Structure', title: 'How to Choose the Right Custom Box Structure', summary: 'Compare rigid, folding carton, drawer, magnetic and corrugated structures by presentation, protection, volume and production needs.', intro: 'The right box structure is a commercial decision as much as a visual one. It affects tooling, assembly, packing speed, shipping volume, protection and the way a customer first handles the product.', sections: [
    ['Start with the product and sales channel', 'Confirm finished internal dimensions in L × W × H, product weight, fragility, retail or e-commerce use, order quantity and destination. A premium retail launch may justify a rigid presentation box, while a high-volume product may need a folding carton or corrugated mailer.'],
    ['Common premium structures', 'Magnetic book-style rigid boxes create a strong reveal. Drawer boxes offer a controlled slide-out experience. Lift-off lid boxes are versatile and efficient to pack. Folding cartons reduce storage and freight volume. Corrugated structures add transport protection and can still carry premium printing.'],
    ['Balance presentation and logistics', 'A beautiful box that ships mostly empty space can increase total landed cost. Fold-flat constructions, removable inserts and optimized outer cartons may reduce storage and freight, but savings should be confirmed with packed dimensions, carton count, CBM and weight.'],
    ['What to confirm before sampling', 'Approve the exact structure name, internal size, board thickness, opening direction, closure, insert concept, print areas and intended packing method before producing a physical sample.'],
  ]},
  { slug: 'packaging-material-selection', number: '02', angle: 'Materials', title: 'Packaging Material Selection for Premium Boxes', summary: 'Understand greyboard, paperboard, corrugated board, specialty paper and responsible material options without over-specifying cost.', intro: 'Material selection determines stiffness, print behavior, edge quality, weight and tactile character. The most expensive substrate is not automatically the most suitable one.', sections: [
    ['Structural board', 'Rigid boxes commonly use greyboard selected by thickness and density. Folding cartons use paperboard chosen by caliper, stiffness and print surface. Corrugated packaging adds flute selection, compression strength and edge-crush considerations.'],
    ['Wrapping and face paper', 'Coated paper supports detailed offset printing and lamination. Uncoated and textured specialty papers create a more tactile, restrained appearance but may change color reproduction, foil performance and rub resistance.'],
    ['Liners and exposed edges', 'Inside liners affect opening feel, cleanliness and brand color continuity. Wrapped edges, corner construction and paper grain direction influence the finished appearance of premium rigid boxes.'],
    ['Responsible choices', 'FSC-certified papers, recycled content, molded pulp and paper-based inserts can reduce plastic use. Claims should match actual certificates and the complete material specification rather than relying on a generic eco label.'],
  ]},
  { slug: 'printing-finishing-guide', number: '03', angle: 'Print & Finish', title: 'Printing and Finishing for Luxury Packaging', summary: 'Use color, foil, embossing, debossing, spot UV and texture with production tolerances and brand consistency in mind.', intro: 'Finishing should reinforce hierarchy and touch, not simply add decoration. Every process introduces cost, setup requirements and production tolerances that should be considered during artwork development.', sections: [
    ['Color control', 'Specify Pantone or process color intent, the substrate, coating and approved reference. The same ink can appear different on coated paper, uncoated paper and colored specialty stock. Physical proofs remain important for critical brand colors.'],
    ['Foil stamping', 'Metallic, pigment and holographic foils create high contrast without ink. Fine lines, large solid areas, seams and textured paper require different tooling and pressure considerations.'],
    ['Embossing and debossing', 'Raised or recessed details add a tactile focal point. Artwork depth, board backing, register with print or foil and the reverse-side impression should be reviewed before tooling.'],
    ['Lamination, varnish and spot effects', 'Matte or gloss lamination changes color and rub resistance. Spot UV can create contrast but needs practical registration tolerance. Avoid combining processes only because they are available; prioritize the brand’s main visual signal.'],
  ]},
  { slug: 'custom-inserts-product-protection', number: '04', angle: 'Insert & Protection', title: 'Custom Inserts: Presentation, Fit and Product Protection', summary: 'Select paper, molded pulp, EVA or fabric-covered inserts based on fit, fragility, sustainability and the desired unboxing experience.', intro: 'An insert is part of the packaging structure. It controls movement, protects vulnerable areas and establishes how the product is presented when the box opens.', sections: [
    ['Begin with real product dimensions', 'Use measured product dimensions, weight, center of gravity, tolerances and fragile points. Nominal capacity or a product photo is not enough to engineer a secure fit.'],
    ['Paper and molded pulp', 'Folded paperboard inserts offer printability and recyclability. Molded pulp supports complex forms and plastic reduction, but tooling, surface texture and dimensional tolerance must suit the product.'],
    ['Foam and fabric-covered inserts', 'EVA and other foams provide cushioning and precise cavities. Fabric or paper wrapping improves presentation. Density, thickness, odor, color transfer and adhesive performance should be sampled.'],
    ['Test the complete pack', 'Evaluate insertion and removal, shake movement, compression, drop risk and the outer shipping carton—not only the insert on a desk. Final performance depends on the complete packaging system.'],
  ]},
] as const;

export function getArticle(slug: string) { return articles.find((article) => article.slug === slug); }
