import {normalizeSizePlan} from './size-plan.mjs';
import {normalizeSet} from './packaging-set.mjs';
import {buildBox} from './packaging.mjs';
import {availableFaces,imagePlacement} from './image-placement.mjs';
import {isSafeImage,normalizeArtwork} from './artwork.mjs';
import {previewOptions} from './gift-preview.mjs';
export const GOALS=['Premium Presentation','Best Value','Lower Shipping Volume','Sustainable Direction','Stronger Protection'];
export const INSERTS={none:{name:'None — review protection needs'},paper:{name:'Paper insert'},eva:{name:'EVA insert'},foam:{name:'Foam insert'}};
export const MATERIALS=[{id:'coated',name:'Coated wrapping paper',categories:['rigid']},{id:'special',name:'Specialty wrapping paper',categories:['rigid']},{id:'white-card',name:'White paperboard',categories:['carton','bag']},{id:'kraft',name:'Kraft paperboard',categories:['carton','bag','corrugated']},{id:'e-flute',name:'E-flute corrugated board',categories:['corrugated']},{id:'b-flute',name:'B-flute corrugated board',categories:['corrugated']}];
export const FINISHES=[{id:'matte-film',name:'Matte lamination'},{id:'gloss-film',name:'Gloss lamination'},{id:'foil',name:'Foil stamping'},{id:'emboss',name:'Emboss / deboss'},{id:'spot-uv',name:'Spot UV'},{id:'window',name:'Window patch'},{id:'magnet',name:'Magnetic closure'},{id:'rope',name:'Handle cord'}];
export const STRUCTURES={tianlide:'Lift-off lid box',drawer:'Drawer box',flip:'Hinged lid box',book:'Book-style box',foldable_flip:'Fold-flat hinged box',window_flip:'Window hinged box',double_door:'Double-door box',shoulder:'Shoulder box',airplane:'Mailer box',rsc:'Shipping carton',tuck:'Tuck-end carton',paperbag:'Paper shopping bag'};
export const DISCLAIMER='Preliminary packaging direction. Engineering review required. Formal quote after specification review. Screen previews do not replace physical sampling or production approval.';
const text=(v,max=150)=>String(v??'').slice(0,max),num=(v,f=0,max=5000)=>Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=max?Number(v):f;
const dimensions=(d={})=>({length:num(d.length),width:num(d.width),height:num(d.height)});
export function normalizeV21(p={}){const product=p.product||{},th=p.thresholds||{};return {product:{name:text(product.name??p.name),category:text(product.category||'general',60),dimensions:dimensions(product.dimensions||p.dimensions),weight:num(product.weight,0,100000),quantity:num(product.quantity,500,1000000),market:text(product.market),fragile:product.fragile===true,productImage:isSafeImage(product.productImage)?product.productImage:'',referenceImage:isSafeImage(product.referenceImage)?product.referenceImage:''},goal:GOALS.includes(p.goal)?p.goal:GOALS[0],insert:Object.hasOwn(INSERTS,p.insert)?p.insert:'none',thresholds:{safeZoneMm:num(th.safeZoneMm,3,100),minDpi:num(th.minDpi,150,600),paddingMm:num(th.paddingMm,5,100)},rawUnsupported:text(p.rawUnsupported),parentId:text(p.parentId,100),solutionId:text(p.solutionId,100)}};
export function sanitizeProject(p={}){const type=Object.hasOwn(STRUCTURES,p.type)?p.type:'tianlide',category=buildBox(type,p.dimensions).category,material=MATERIALS.find(m=>m.id===p.materialId&&m.categories.includes(category))||MATERIALS.find(m=>m.categories.includes(category));return {schemaVersion:'public-1',sizePlan:normalizeSizePlan(p),accessories:normalizeSet(p.accessories),id:text(p.id||crypto.randomUUID(),100),name:text(p.name||p.product?.name||'New project'),type,dimensions:dimensions(p.dimensions||{length:200,width:140,height:60}),...normalizeV21(p),materialId:material.id,boardMaterial:text(p.boardMaterial|| (category==='rigid'?'Greyboard — thickness to be reviewed':material.name)),wrappingMaterial:text(p.wrappingMaterial||(category==='rigid'?material.name:'None / direct print')),printMethod:['offset','digital','flexo'].includes(p.printMethod)?p.printMethod:'offset',colorCount:num(p.colorCount,4,8),crafts:Array.isArray(p.crafts)?[...new Set(p.crafts.filter(id=>FINISHES.some(f=>f.id===id)))]:[],artworks:(Array.isArray(p.artworks)?p.artworks:[]).slice(0,20).map(a=>{if(!['text','image'].includes(a.kind)||a.kind==='image'&&!isSafeImage(a.src))throw Error('Unsupported artwork. Please use PNG, JPG or WebP.');const n=normalizeArtwork(a);return {id:text(a.id||crypto.randomUUID(),100),kind:a.kind,face:n.face,x:n.x,y:n.y,size:n.size,color:n.color,finish:n.finish,fit:n.fit||'contain',...(['logo','photo','background'].includes(a.usage)?{usage:a.usage}:{}),...(a.kind==='image'?{src:a.src,name:text(a.name),pixelWidth:num(a.pixelWidth,0,20000),pixelHeight:num(a.pixelHeight,0,20000)}:{text:text(a.text,300)}),...Object.fromEntries(['hidden','locked','whiteBackground','hasTransparency','maskConfirmed'].filter(k=>typeof a[k]==='boolean').map(k=>[k,a[k]]))}}),visualOptions:previewOptions(p.visualOptions),recommendationReason:text(p.recommendationReason,800),updatedAt:text(p.updatedAt||new Date().toISOString(),40)};}
export function parsePublicProject(raw){if(typeof raw!=='string'||raw.length>12000000)throw Error('Project exceeds 12 MB.');const data=JSON.parse(raw);if(!['mtt-public-packaging-project','packaging-quote-project'].includes(data.format)||!data.project?.id||!Object.hasOwn(STRUCTURES,data.project.type)||!Array.isArray(data.project.artworks)||data.project.artworks.length>20)throw Error('Invalid packaging project.');return sanitizeProject(data.project);}
export function exportPublicProject(p){return JSON.stringify({format:'mtt-public-packaging-project',version:1,project:sanitizeProject(p)},null,2);}
export function solutions(project){const {product,goal,thresholds}=normalizeV21(project),eco=goal===GOALS[3],protect=goal===GOALS[4]||product.fragile||product.weight>2;const base=goal===GOALS[2]?'foldable_flip':protect?'airplane':product.category==='apparel'?'paperbag':product.category==='cosmetic'?'tuck':'tianlide';const value=base==='tuck'?'airplane':base==='paperbag'?'tuck':product.category==='apparel'?'paperbag':'tuck';return [base,value,base==='foldable_flip'?'airplane':'foldable_flip'].map((type,i)=>{const category=buildBox(type,project.dimensions).category,economy=i===1||eco,premium=i===0&&goal===GOALS[0],materialId=category==='rigid'?(premium?'special':'coated'):category==='corrugated'?'e-flute':economy?'kraft':'white-card';return {id:['recommended','value','alternative'][i],title:['Recommended','Best Value','Alternative / Lower Freight'][i],type,materialId,boardMaterial:category==='rigid'?'Greyboard — thickness to be reviewed':MATERIALS.find(m=>m.id===materialId).name,wrappingMaterial:category==='rigid'?MATERIALS.find(m=>m.id===materialId).name:'None / direct print',insert:product.fragile?(eco||i===1?'paper':'foam'):'none',crafts:category==='corrugated'||economy?[]:premium?['matte-film','foil']:['matte-film'],printMethod:category==='corrugated'?'flexo':'offset',colorCount:4,visualOptions:{paperColor:premium?'#244438':economy?'#ba9660':'#eee8da',surface:'matte',opening:0},dimensions:{length:product.dimensions.length+thresholds.paddingMm*2,width:product.dimensions.width+thresholds.paddingMm*2,height:product.dimensions.height+thresholds.paddingMm*2},advantages:i===1?'Fewer added finishes for a simpler packaging direction.':i===2?'A flat-pack shipping direction to review with MTT.':'A starting direction for your selected product and goal.',cautions:'Structure, fit, material suitability and protection require engineering review and physical sampling. No freight savings or sustainability certification is guaranteed.',recommendationReason:`Based on ${goal}, ${product.category}${product.fragile?', fragile product':''}${product.weight>2?', weight screening above 2 kg (not a load rating)':''}. ${i===2?'Actual shipping volume must be reviewed.':''}`};});}
export function preflight(project){const meta=normalizeV21(project),issues=[],add=(severity,code,message)=>issues.push({severity,code,message});
 for(const [label,dim] of [...(normalizeSizePlan(project).mode==='product'?[['Product',project.product?.dimensions]]:[]),['Internal box',project.dimensions]])if(!dim||!['length','width','height'].every(k=>Number.isFinite(Number(dim[k]))&&Number(dim[k])>0&&Number(dim[k])<=5000))add('Error','dimensions',`${label} dimensions are missing, invalid or exceed the 5000 mm tool limit.`);
 if(!Number.isInteger(Number(project.product?.quantity))||Number(project.product?.quantity)<1||Number(project.product?.quantity)>1000000)add('Error','quantity','Enter a whole quantity from 1 to 1,000,000.');
 if(meta.product.fragile&&meta.insert==='none')add('Warning','insert','Fragile product has no insert; protection needs engineering review.');
 if(normalizeSizePlan(project).mode==='product'&&['length','width','height'].some(k=>Number(project.product?.dimensions?.[k])>Number(project.dimensions?.[k])))add('Error','fit','Product exceeds the corresponding internal box dimensions; rotation has not been assumed.');
 if(meta.rawUnsupported)add('Error','raw-file',`不支持的原始文件：${meta.rawUnsupported}。请使用 PNG/JPG/WebP，或由设计师转换。`);
 const d=project.dimensions||{},faces=availableFaces(project.type);let maskFinishes=new Set;
 for(const a of project.artworks||[]){if(a.hidden)continue;const name=a.name||a.text||'图案';if(!faces.includes(a.face)){add('Error','unsupported-face',`${name} 所选面暂不支持整图贴图`);continue}
 const fw=['left','right'].includes(a.face)?Number(d.width):Number(d.length),fh=['top','bottom'].includes(a.face)?Number(d.width):Number(d.height);if(!(fw>0&&fh>0))continue;
 const rect=a.kind==='image'&&a.pixelWidth&&a.pixelHeight?imagePlacement(a.pixelWidth,a.pixelHeight,fw,fh,a.size,a.fit||'contain'):{width:fw*a.size/100,height:fh*a.size/100,boxWidth:fw*a.size/100,boxHeight:fh*a.size/100};
 const width=a.fit==='cover'?rect.boxWidth:rect.width,height=a.fit==='cover'?rect.boxHeight:rect.height;const edges=[fw*a.x/100-width/2,fw-fw*a.x/100-width/2,fh*a.y/100-height/2,fh-fh*a.y/100-height/2];
 if(edges.some(v=>v<-.01))add('Error','outside',`${name} is outside the face; reduce its size or center it.`);else if(edges.some(v=>v<meta.thresholds.safeZoneMm))add('Warning','safe-zone',`${name} is closer to the edge than the configured ${meta.thresholds.safeZoneMm}mm safe zone`);
 if(a.kind==='image'){if(!isSafeImage(a.src))add('Error','raw-file',`${name} 不是受支持的本机图片`);if(!a.pixelWidth||!a.pixelHeight)add('Warning','resolution-unknown',`${name} 缺少像素资料，请重新上传以检查分辨率`);else{const dpi=Math.min(a.pixelWidth/(rect.width/25.4),a.pixelHeight/(rect.height/25.4));if(dpi<meta.thresholds.minDpi)add('Warning','resolution',`${name} effective resolution is approximately ${Math.round(dpi)} DPI, below the configured ${meta.thresholds.minDpi} DPI`)}if(a.whiteBackground!==false)add('Warning','white-background',`${name} white background is unconfirmed; check whether removal is needed.`);}
 if(['gold','silver','uv','emboss'].includes(a.finish)){if(a.kind==='text'||a.maskConfirmed||a.hasTransparency){maskFinishes.add(a.finish)}else add('Warning','mask',`${name} 的 ${a.finish} 尚未确认独立工艺蒙版`)}
 }
 for(const [id,finishes] of [['foil',['gold','silver']],['spot-uv',['uv']],['emboss',['emboss']]])if((project.crafts||[]).includes(id)&&!finishes.some(f=>maskFinishes.has(f)))add('Warning','mask',`${id} is selected without a corresponding visible artwork mask.`);
 return{status:issues.some(i=>i.severity==='Error')?'Error':issues.length?'Warning':'Ready',issues};
}
export function historyPush(history,current,next){return{past:[...history.past,current],present:next,future:[]};}
export function historyUndo(history){if(!history.past.length)return history;return{past:history.past.slice(0,-1),present:history.past.at(-1),future:[history.present,...history.future]};}
export function historyRedo(history){if(!history.future.length)return history;return{past:[...history.past,history.present],present:history.future[0],future:history.future.slice(1)};}
