const dimension=value=>Number(value.toFixed(1));
const escapeXml=value=>String(value).replace(/[<>&"']/g,char=>({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&apos;"}[char]));
export function layoutPieces(box,gap=24){let y=gap,maxW=0;const placed=box.pieces.map(item=>{const offsetX=gap-item.bounds.x,offsetY=y-item.bounds.y;y+=item.bounds.h+gap;maxW=Math.max(maxW,item.bounds.w);return{...item,offsetX,offsetY}});return{pieces:placed,width:maxW+gap*2,height:y}}
export function dielineSvg(box,artworks=[]){const layout=layoutPieces(box,64);const used=new Set;const body=layout.pieces.map(item=>`<g data-piece="${escapeXml(item.id)}">${item.panels.map(panel=>{const art=artworks.filter(value=>!value.hidden&&value.face===panel.face&&!used.has(value.id));art.forEach(value=>used.add(value.id));const designs=art.map(value=>{const x=panel.x+item.offsetX+panel.w*value.x/100,y=panel.y+item.offsetY+panel.h*value.y/100,size=Math.min(panel.w,panel.h)*value.size/100;if(value.kind==="image"&&/^data:image\//.test(value.src||""))return`<svg x="${x-panel.w*value.size/200}" y="${y-panel.h*value.size/200}" width="${panel.w*value.size/100}" height="${panel.h*value.size/100}" overflow="hidden"><image href="${escapeXml(value.src)}" x="0" y="0" width="100%" height="100%" preserveAspectRatio="xMidYMid ${value.fit==='cover'?'slice':'meet'}"/></svg>`;return`<text x="${x}" y="${y}" style="font-size:${Math.max(6,size)}px;fill:${/^#[0-9a-f]{6}$/i.test(value.color||"")?value.color:"#17212b"}" class="art-text">${escapeXml(value.text||"")}</text>`}).join("");return`<rect x="${panel.x+item.offsetX}" y="${panel.y+item.offsetY}" width="${panel.w}" height="${panel.h}" class="cut"/>${panel.window?`<rect x="${panel.x+item.offsetX+panel.window.x}" y="${panel.y+item.offsetY+panel.window.y}" width="${panel.window.w}" height="${panel.window.h}" fill="#dfede8" stroke="#d23b3b"/>`:""}<text x="${panel.x+item.offsetX+panel.w/2}" y="${panel.y+item.offsetY+panel.h/2}" class="label">${escapeXml(panel.name)}</text>${designs}<text x="${panel.x+item.offsetX+panel.w/2}" y="${panel.y+item.offsetY+panel.h/2+18}" class="dimension" style="font-size:${Math.min(15,Math.max(6,panel.w/9))}px">${dimension(panel.w)} × ${dimension(panel.h)} mm</text>`}).join("")}${foldLines(item)}<text x="${item.offsetX+item.bounds.x}" y="${item.offsetY+item.bounds.y-42}" class="piece-label">${escapeXml(item.name)}</text>${pieceDimensions(item)}</g>`).join("");return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${layout.width} ${layout.height}" width="${layout.width}mm" height="${layout.height}mm"><style>.cut{fill:#fffdf8;stroke:#d23b3b;stroke-width:1;vector-effect:non-scaling-stroke}.label{font:14px sans-serif;text-anchor:middle;fill:#53606b}.piece-label{font:bold 16px sans-serif;fill:#17212b}.art-text{text-anchor:middle;font-family:sans-serif;font-weight:bold}.dimension{font:bold 15px sans-serif;text-anchor:middle;fill:#145f50;paint-order:stroke;stroke:#fffdf8;stroke-width:3px;stroke-linejoin:round}.measure{stroke:#145f50;stroke-width:1;fill:none;vector-effect:non-scaling-stroke}.fold{stroke:#2877c7;stroke-dasharray:5 4}</style>${body}<text x="${layout.width/2}" y="${layout.height-12}" class="dimension" style="font-size:${Math.min(15,layout.width/45)}px">mm · Structural reference only — engineering review required</text></svg>`}
export function bomRows(box,materialName=box.material){return box.pieces.map((item,index)=>({no:index+1,name:item.name,material:materialName,size:`${item.bounds.w} × ${item.bounds.h} mm`,areaM2:Math.round(item.panels.reduce((sum,p)=>sum+p.w*p.h,0)/100)/10000,quantity:1,notes:item.notes.join("；")||"按结构图开料"}))}
export function faceDimensions(box){const {length,width,height}=box.dimensions;return{front:{w:length,h:height},back:{w:length,h:height},left:{w:width,h:height},right:{w:width,h:height},top:{w:length,h:width},bottom:{w:length,h:width}}}

function pieceDimensions(item){
 const x=item.offsetX+item.bounds.x,y=item.offsetY+item.bounds.y,w=item.bounds.w,h=item.bounds.h;
 return `<g aria-label="Overall blank dimensions"><path class="measure" d="M ${x} ${y-16} H ${x+w} M ${x} ${y-22} V ${y-10} M ${x+w} ${y-22} V ${y-10} M ${x+w+18} ${y} V ${y+h} M ${x+w+12} ${y} H ${x+w+24} M ${x+w+12} ${y+h} H ${x+w+24}"/><text class="dimension" x="${x+w/2}" y="${y-22}">${dimension(w)} mm</text><text class="dimension" transform="translate(${x+w+38} ${y+h/2}) rotate(-90)">${dimension(h)} mm</text></g>`;
}

function foldLines(item){return item.panels.map(p=>{let lines=(p.creases||[]).map(l=>[p.x+l[0],p.y+l[1],p.x+l[2],p.y+l[3]]);if(p.fold){const q=item.panels.find(v=>v.id===p.fold.parent),edge=p.fold.edge;if(edge==='left'||edge==='right'){const x=edge==='left'?q.x:q.x+q.w;lines.push([x,Math.max(p.y,q.y),x,Math.min(p.y+p.h,q.y+q.h)])}else{const y=edge==='top'?q.y:q.y+q.h;lines.push([Math.max(p.x,q.x),y,Math.min(p.x+p.w,q.x+q.w),y])}}return lines.map(l=>`<path class="fold" fill="none" stroke-width="1.2" vector-effect="non-scaling-stroke" d="M ${l[0]+item.offsetX} ${l[1]+item.offsetY} L ${l[2]+item.offsetX} ${l[3]+item.offsetY}"/>`).join('')}).join('')}
